### ISSUE TITLE
Avoid libstdc++ dependency?

### ISSUE THREAD

**Issue by afcowie** [bos/text-format#13]
Is there a way **text-format** could be done without needing **double-conversion**? Bringing in a dependency on `libstdc++` is rather heavy; certainly it wasn't a standard install in the minimal containers our Haskell static binaries were working just fine within until we started using @chrisdone's awesome **formatting** package this week.

I realize full well you've gone to a lot of trouble to wrap the C++ library doing that work of showing doubles that **text-format** delegates to. I assume the answer is that someone would have to write a pure C implementation of the algorithm. And _yes_ I can tell our build scripts and Dockerfiles and what not to install `libstdc++` as a prerequisite. Just wanted to ask if there was any thought of evolving this.

Sure, it's "only" 1.1 MB extra for that dependency, but that's a lot when trying to build minimal containers. Now that you know the algorithm do you still need the V8 derived codebase to make it work?

Anyway, is there any future where **text-format** does not depend on **double-conversion**? If it's not a non-starter, then what would you need from the community?

AfC

**Comment by bos** [comment]
If you would like to port double-conversion to Haskell or plain C, that would be quite helpful. Otherwise, I don't plan to change the dependency here.
